
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 19 14:22:29 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 40;
  public static final int GREATER_OR_EQUAL = 30;
  public static final int CONST = 5;
  public static final int PERIOD = 39;
  public static final int LPAREN = 12;
  public static final int GREATER = 29;
  public static final int SEMI = 8;
  public static final int CONTINUE = 17;
  public static final int LESS = 31;
  public static final int MINUS = 34;
  public static final int CHARACTER = 47;
  public static final int RPAREN = 13;
  public static final int AND = 26;
  public static final int LESS_OR_EQUAL = 32;
  public static final int OR = 25;
  public static final int BOOL = 46;
  public static final int COMMA = 7;
  public static final int INC = 23;
  public static final int DIV = 36;
  public static final int PLUS = 33;
  public static final int IF = 14;
  public static final int IS_EQUAL = 27;
  public static final int IS_NOT_EQUAL = 28;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int EQUAL = 6;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int NUMBER = 45;
  public static final int MOD = 37;
  public static final int IDENT = 44;
  public static final int BREAK = 16;
  public static final int VOID = 11;
  public static final int COLON = 42;
  public static final int UNION = 38;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int LSQUARE = 9;
  public static final int READ = 19;
  public static final int RSQUARE = 10;
  public static final int WHILE = 22;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 24;
  public static final int MULTIPLICATION = 35;
  public static final int PRINT = 20;
  public static final int DO = 21;
  public static final int SET = 43;
}

